# Generated by Django 5.1 on 2024-08-27 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
